### ISSUE TITLE
eventHandler before watchX Error, vice versa OK. 

### ISSUE THREAD

**Issue by formvoltron** [escamoteur/flutter_command#11]
I'm not sure if this is even a real need.   I found a situation that causes an error and it isn't clear why it's an error.  

If I use a    
 `registerHandler((StringManager sm) => sm.transformString,
            (context, name, _) => print(name));`
before
    `var message2 = watchX((StringManager sm) => sm.transformString);`

this causes an error.  However if I reverse the order of the statements, there is no error & everything works just fine.

What's going on here?

Thank you!

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_command/flutter_command.dart';
import 'package:get_it/get_it.dart';
import 'package:get_it_mixin/get_it_mixin.dart';

void main() {
  var sm = StringManager();
  GetIt.I.registerSingleton<StringManager>(sm);
  sm.loadStringCommand.execute();

  runApp(MaterialApp(home: MyApp()));
}

class StringManager {
  Command<void, String> loadStringCommand;
  ValueListenable<String> transformString;

  StringManager() {
    loadStringCommand =
        Command.createAsync<void, String>(_stringService, 'initial');

    transformString =
        loadStringCommand.map<String>((result) => result.toUpperCase());
  }

//TODO why is 'void x' needed as a parameter?
  Future<String> _stringService(void x) async {
    await Future.delayed(Duration(seconds: 2));
    return 'thank you for waiting';
  }
}

class MyApp extends StatelessWidget with GetItMixin {
  @override
  Widget build(BuildContext context) {


    var message = watchX((StringManager sm) => sm.loadStringCommand);
    var message2 = watchX((StringManager sm) => sm.transformString);

    registerHandler((StringManager sm) => sm.transformString,
            (context, name, _) => print(name));

    return Scaffold(
      appBar: AppBar(
        title: Text('hello'),
      ),
      body: Column(
        children: [Text(message), Text(message2)],
      ),
    );
  }
}
```

**Comment by Abhilash-Chandran** [comment]
Hi @formvoltron,

I just verified this issue and I am convinced this issue has nothing to do with the `flutter_command`.

The problem arises from the fact that `registerHandler` also calls `watchX` internally and tries to add a watcher for the same `ValueListenable` which in your case in `sm.transformString`.

https://github.com/escamoteur/get_it_mixin/blob/master/lib/src/mixin_state.dart#L72

This question should be posted in [get_it_mixin ](https://github.com/escamoteur/get_it_mixin) repository. I am not sure if this is a bug as the code appears ok. But perhaps it needs some clear documentation about the order of registration.

I will go ahead and close this issue. Please feel free to reopen it if you still think its a `flutter_command` issue. Cheers 😄
