### ISSUE TITLE
internal default (b)=>b command for restrictions

### ISSUE THREAD

**Issue by formvoltron** [escamoteur/flutter_command#12]
Maybe I am missing something, but it seems like a basic:

Command.createSync((b) => b, true);

is what you would always want for the restriction field of the command.   

Does it make sense to have the Command create this command and set it to restriction internally when the Command is constructed?

**Comment by Abhilash-Chandran** [comment]
I am not sure if I understood your question. As per the documentation you don't have to always set the `restriction` field. Its only a property that allows you to block the command execution externally other than the internal flags such as `isExecuting`  and `canExecute`.

Could you please briefly explain what you are intending to achieve. Sorry that I am not able to grasp your point.

**Comment by formvoltron** [comment]
I probably do not understand this well enough, but...  

In the case that you do want to use the restriction field, would you ever want a different command than Command.createSync((b) => b, true)?

**Comment by Abhilash-Chandran** [comment]
It is not necessary to have Command for this. A simple `ValueNotifier` is enough. As you can see `restriction` accepts a `ValueListenable`. For e.g.

```dart
ValueNotifier<bool> userHasPermissionToSearch  = ValueNotifier<bool>(false);
```

You can pass `userHasPermissionToSearch` as a `restriction` field of a Command that performs search. This way you allow performing the search only if the user is allowed to do so, which will be set as `userHasPermissionToSearch.value=true` in a separate business logic say `decideIfUserCanPerformSearch()`.

The `restriction` functionality can also be used for cases where you want to restrict execution of one `command` when another `command` is already in progress by connecting the `isExecuting` of one `command` to the other. 
For e.g.

Let us assume you want to validate if the user's session is valid on a periodic basis. You can restrict the user from performing any search  whenever the validation of the session is in progress by connecting these two commands.

**user_manager.dart**
```dart
Future<bool> methodToValidateSession() async{
 /// logic to validate session.
}
Command<void, bool> isUserSessionValid = Command.createAsyncNoParam<bool>( methodToValidateSession, false);
```

**search_manager.dart**
```dart
Future<List<String>> getCityNames(String country) async {
 /// time consuming logic to fetch City Names ;-)
}

Command<String, List<String>> fetchCityNames =
    Command.createAsync<String, List<String>>(
  getCityNames,
  [],
  restriction: userManager.isUserSessionValid.isExecuting,
);
```
Ideally for this case you would disable the button performing the search, but this is just a show case example. 😃

**Comment by escamoteur** [comment]
you actually can use `fetchCitiyNames.canExecute` ValuenNotifier to enable/disable your Button.
