### ISSUE TITLE
Handling Streams

### ISSUE THREAD

**Issue by TC3000** [escamoteur/flutter_command#15]
What is the best approach to handle streams? Say, I want to listen to a stream of data from firestore for example, what do I use? There's `createAsync` which takes in a function that returns a future. There's also `createSync` which expects a value, well, what about streams? Maybe have a `createStream` property??

**Comment by aquilarafa** [comment]
I think controlling streams would hurt the purpose of this package. Maybe you could create an adapter from firestore streams to a Listenable.

**Comment by escamoteur** [comment]
I'm also not sure if it's a good idea to add that. To me it's also not clear what should happen to the stream when the command is executed

**Comment by TC3000** [comment]
What happens to a `future` when a command is executed? Fetch the data and return the result, right? Let's do the same thing with streams.

**Comment by escamoteur** [comment]
Yes but a future happens only once. A Stream can emit items indefinitely. How does that fit with a command that is executed once?
Am 6. Feb. 2022, 16:27 +0100 schrieb TC3000 ***@***.***>:

**Comment by TC3000** [comment]
Perhaps, my way of asking is wrong here, let's try this..

I think its the manager's responsibility to handle streams, that's opening, listening and closing, It shouldn't be up to the ui layer, nor to the service layer. 

Coming from the bloc library, there were recommended approaches for almost everything, from how to handle synchronous data, `futures`, `streams`, `debouncing`, pagination, etc etc. 

Having said that, what is the recommended approach of handling streams that anyone interested in flutter_command should follow?

**Comment by escamoteur** [comment]
I think it's not easy to give a general recommendation here. 
If you could lay out a bit more what you would like it to do with a stream that would still be in the context of a command. 

if I need a Stream I probably would not use it directly together with a command.
