### ISSUE TITLE
Conceptual issue around the use of GeIt and Singleton

### ISSUE THREAD

**Issue by BSBoatia** [escamoteur/flutter_command#16]
All,

we have recently implemented flutter_commands. First of all thank you very much for this great package. 

We've run into an issue though, which is more of a conceptual issue around the use of GeIt and Singleton than a software bug. I would really appreciate your thoughts on this though.

Our goal is to create self sustained widgets that can be used throughout the app. With self sustained, I mean a widget that could be added somewhere in the widget tree without the need to explicitly handle the widgets (or views) functionality within the parent. Everything that needs to be managed with respect to the widgets view is contained in the widgets own manager.

**For example**
A stateful AtmosphericPressureTrend widget that is cyclically loading pressure data from a database and displaying it as a simple trend icon (stable, up, down, ...). We're initializing the widgets manager (AtmosphericPressureTrendDataManager) within initState() of the widget to use the command as valueListenable inside the build method

```
    if (!getIt.isRegistered<AtmosphericPressureTrendDataManager>()) {
      getIt.registerSingleton<AtmosphericPressureTrendDataManager>(
          AtmosphericPressureTrendDataManager());
    }
```

and disposing of it in dispose()
```
    if (getIt.isRegistered<AtmosphericPressureTrendDataManager>()) {
      getIt<AtmosphericPressureTrendDataManager>().dispose();
      getIt.unregister<AtmosphericPressureTrendDataManager>();
    }
```

Disposing is important as resources, such as the refresh timer running (an ultimately executing the command) in the widgets manager need to be cleaned up.

**So far so good, it's working splendidly!**

The issue arises when the widget is also included in a screen that is push replacing the current screen (both screens containing an AtmosphericPressureTrend widget):

`Navigator.of(context).pushReplacement(_'new screen containing widget'_)`

Flutter is initializing the state of the widget on the new screen before disposing of the "old" widget. This unregisters AtmosphericPressureTrendDataManager from GetIt after the init of the new widget :(

```
flutter: AtmosphericPressureTrend init state
flutter: registerSingleton<AtmosphericPressureTrendDataManager>
flutter: AtmosphericPressureTrendDataManager()
flutter: AtmosphericPressureTrend refresh data
```
– CHANGE OF SCREEN --
```
flutter: AtmosphericPressureTrend init state
flutter: AtmosphericPressureTrendDataManager already registered
**top: output from new widget / down: output from old widget**
flutter: AtmosphericPressureTrendDataManager dispose
flutter: unregister<AtmosphericPressureTrendDataManager> 
```
Bäääm!

This is a bit unfortunate. We could push replace to an intermediate screen, but that's pretty ugly. Any thoughts or input on this is highly appreciated!

Thx.

**Comment by escamoteur** [comment]
Hi,

I wouldn't register/unregister that manager withing the widget. I would register it only at startup but give the manager a `addClient`  `removeClient` function. then you keep track of the amount of clients. if clients changes from 0 to 1 you start the timer and stop it when the last client is removed. then you use the add/remove function int your widgets `initState` and `dispose`

**Comment by BSBoatia** [comment]
Thanks a lot @escamoteur, we finalized testing today. The approach ist working very well!
