### ISSUE TITLE
Reach out for an freelance job opportunity

### ISSUE THREAD

**Issue by eugenebrusov** [escamoteur/flutter_command#19]
Hey Thomas @escamoteur ,

Sorry to bother you and spam you this way. Looked through all your profiles and wasn't able to find any way to reach you except for this ugly one.

Looked through your GitHub repositories and found that you have an outstanding experience in Flutter, especially RxDart.

My name is Eugene Brusov and I'm currently working as Lead Mobile Developer for US based company ForwardEdge https://www.forwardedge.ai/ And they are currently looking to expand their team with Flutter developers.

Are you open for new jobs/opportunities?

**Comment by escamoteur** [comment]
unfortunately I'm in a project for the next months
