### ISSUE TITLE
Unhandled error when a command has an error with an empty StringStackTrace

### ISSUE THREAD

**Issue by tpucci** [escamoteur/flutter_command#20]
Hello escamoteur and thanks for this great lib !

_Version: 5.0.0+16_
I noticed an issue in the `_improveStacktrace` function.

When passed an empty StringStackTrace as such...
<img width="400" alt="image" src="https://github.com/escamoteur/flutter_command/assets/16262904/77666796-d040-40f7-a540-0ec44743f8e7">

...then `strippedFrames` is an empty list and the following throws an exception:

<img width="447" alt="image" src="https://github.com/escamoteur/flutter_command/assets/16262904/932223d5-0d16-4488-bbf8-d891bdf47f0b">

Couldn't point to the code in the repo as I can't locate `_improveStacktrace` 😅

Cheers !

**Comment by escamoteur** [comment]
fixed in 5.0.0+17
